on: [push, workflow_dispatch]


jobs:
  macos:
    runs-on: macos-10.15
    steps:
      - run: curl -L https://libsdl.org/release/SDL2-2.0.14.tar.gz | tar xzf -
      - run: ./configure
          --disable-shared
          --enable-static
          --disable-audio
          --disable-video
          --disable-render
          --disable-video-vulkan
          --prefix=/usr/local/SDL2-2.0.14
        working-directory: SDL2-2.0.14
      - run: make
        working-directory: SDL2-2.0.14
      - run: make install DESTDIR=$PWD/../deploy
        working-directory: SDL2-2.0.14
      - uses: actions/upload-artifact@v2
        with:
          name: sdl2-macos-static
          path: deploy
