name: Build - Windows

on: [push, workflow_dispatch]

env:
  SDL_NAME: SDL2-2.0.20
  PLATFORM_SUFFIX: mingw


jobs:
  mingw:
    runs-on: ubuntu-20.04
    steps:
      - name: APT deps
        run: |
          sudo apt-get update && sudo apt-get install -y g++-mingw-w64-i686
          echo 1 | sudo update-alternatives --config i686-w64-mingw32-gcc
          echo 1 | sudo update-alternatives --config i686-w64-mingw32-g++
      - uses: actions/checkout@v3
      - run: ./tools/common_build.sh --host=i686-w64-mingw32
      - uses: actions/upload-artifact@v2
        with:
          name: sdl2-mingw-static
          path: deploy/*.tar.xz
