name: Build - Windows

on: [push, workflow_dispatch]

env:
  SDL_NAME: SDL2-2.0.20


jobs:
  mingw:
    runs-on: ubuntu-20.04
    steps:
      - name: APT deps
        run: |
          sudo apt-get update && sudo apt-get install -y g++-mingw-w64-i686
          echo 1 | sudo update-alternatives --config i686-w64-mingw32-gcc
          echo 1 | sudo update-alternatives --config i686-w64-mingw32-g++
      - run: curl -L https://libsdl.org/release/${SDL_NAME}.tar.gz | tar xzf - --strip-components=1
      - name: Configure
        run: ./configure
          --disable-shared
          --enable-static
          --disable-audio
          --disable-render
          --disable-video-dummy
          --disable-video-vulkan
          --host=i686-w64-mingw32
          --prefix=/opt/${SDL_NAME}
      - run: make
      - run: make install DESTDIR=$PWD/deploy
      - run: tar cJf ../${SDL_NAME}_mingw.tar.xz ./*
        working-directory: deploy/opt
      - uses: actions/upload-artifact@v2
        with:
          name: sdl2-mingw-static
          path: deploy/*.tar.xz
