name: Build - Mac

on: [push, workflow_dispatch]

env:
  SDL_NAME: SDL2-2.24.1
  PLATFORM_SUFFIX: macos


jobs:
  macos:
    runs-on: macos-11
    env:
      MACOSX_DEPLOYMENT_TARGET: "10.15"
    steps:
      - uses: actions/checkout@v3
      - run: ./tools/common_build.sh --disable-video
      - uses: actions/upload-artifact@v2
        with:
          name: sdl2-macos-static
          path: deploy/*.tar.xz
